[package]
name = "fritzbox_logs"
version = "0.1.0"
authors = ["mexus <gilaldpellaeon@gmail.com>"]

[dependencies]
chrono = "0.4"
regex = "0.2"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
quick-error = "1.2.1"
